PAGE_SIZE = 1024 * 8
BYTE_ORDER = "little"
HDR_SIZE = 24
MAX_PAGE_COUNT = 256
META_SIZE = 256

PAGE_TYPE_ROOT = 1
PAGE_TYPE_INTERNAL = 2
PAGE_TYPE_DATA = 3
PAGE_TYPE_HEAP = 4

MAX_KEY_COUNT = 2
MAX_SLOT_COUNT = MAX_KEY_COUNT + 1
BTREE_DETAIL_HDR_SIZE = 8 + 8 + (8*(MAX_SLOT_COUNT-1)) + (8 * MAX_SLOT_COUNT)

BUFFER_CURSOR_DEBUG = False